options:
  merge-default-rules: true

files:
  include: 'system-addon/content-src/**/*.scss'


rules:
  extends-before-declarations: 2
  extends-before-mixins: 2
  force-element-nesting: 0
  force-pseudo-nesting: 0
  hex-notation: [2, {style: uppercase}]
  indentation: [2, {size: 2}]
  leading-zero: [2, {include: true}]
  mixins-before-declarations: [2, {exclude: [breakpoint, mq]}]
  nesting-depth: [2, {max-depth: 4}]
  no-debug: 1
  no-duplicate-properties: 2
  no-misspelled-properties: [2, {extra-properties: [-moz-context-properties]}]
  no-url-domains: 0
  no-vendor-prefixes: 0
  no-warn: 1
  placeholder-in-extend: 2
  property-sort-order: 0

