const {readURI} = require("sdk/net/url");
const {data} = require("sdk/self");
const {PrefsTarget} = require("sdk/preferences/event-target");
const {findClosestLocale, getPreferedLocales} = require("sdk/l10n/locale");
const Feed = require("../lib/Feed");
const am = require("../../common/action-manager");
const {Cu} = require("chrome");

// TODO: These should be generated by a build script
const AVAILABLE_LOCALES = ["en-US"];
const DEFAULT_LOCALE = "en-US";
const FALLBACK_STRINGS = require("../../locales/en-US/strings.json");

// These all affect getPreferedLocales
const LOCALE_PREFS = [
  "intl.locale.matchOS",
  "general.useragent.locale",
  "intl.accept_languages"
];

class LocalizationFeed extends Feed {
  constructor(options) {
    super(options);
    this.availableLocales = options.availableLocales || AVAILABLE_LOCALES;
    this.prefsTarget = PrefsTarget();
    this.onPrefChange = this.onPrefChange.bind(this);
  }
  onPrefChange(pref) {
    this.refresh(`${pref} pref was updated`);
  }
  addListeners() {
    LOCALE_PREFS.forEach(pref => this.prefsTarget.on(pref, this.onPrefChange));
  }
  removeListeners() {
    LOCALE_PREFS.forEach(pref => this.prefsTarget.removeListener(pref, this.onPrefChange));
  }
  getData() {
    let locale = findClosestLocale(this.availableLocales, getPreferedLocales());
    return readURI(data.url(`locales/${locale}/strings.json`))
      .then(strings => JSON.parse(strings))
      .catch(err => {
        Cu.reportError(err);
        locale = DEFAULT_LOCALE;
        return FALLBACK_STRINGS;
      })
      .then(strings => am.actions.Response("LOCALE_UPDATED", {locale, strings}));
  }
  onAction(state, action) {
    switch (action.type) {
      case am.type("APP_INIT"):
        this.addListeners();
        this.refresh("app was initializing");
        break;
      case am.type("APP_UNLOAD"):
        this.removeListeners();
    }
  }
}

LocalizationFeed.AVAILABLE_LOCALES = AVAILABLE_LOCALES;
LocalizationFeed.LOCALE_PREFS = LOCALE_PREFS;

module.exports = LocalizationFeed;
